name = "habit-tracker"
main = "src/index.tsx"
compatibility_date = "2024-05-01"

[vars]
CF_ACCESS_TEAM_DOMAIN = "mutedwarf"
CF_ACCESS_AUD = "a881e48874d7c8a1ee4deec33b9307840ee58c5a82902f39207e2eddcdbf829b"

[[d1_databases]]
binding = "DB"
database_name = "habit-tracker-db"
database_id = "03b05265-c5e8-4477-9837-42fa0cea8868"
